language: scala
sudo: required
dist: trusty
env:
  global:
    - _JAVA_OPTIONS="-Xmx1500m -XX:MaxPermSize=512m -Dakka.test.timefactor=3"
    - SPARK_HOME=/tmp/spark-1.6.2-bin-hadoop2.6
scala:
   - 2.10.6
   - 2.11.8
jdk:
   - oraclejdk8
before_install:
  - sudo apt-get -qq update
script:
  - sbt clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)